disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Pranay Nidhi's Bunker"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Here, you will find out about me, my projects, some writeups and other things."
logo = "image.gif"

[params.author]
name = ""
