[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Whoami"
  pageRef = "whoami"
  weight = 20

[[main]]
  name = "Writeups"
  pageRef = "writeups"
  weight = 30

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 40
